/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MetricConverterGUI;

/**
 *
 * @author Nathan.Davids
 */
public class MetricConverterGUI extends javax.swing.JFrame {

    /**
     * Creates new form MetricConverterGUI
     */
    public MetricConverterGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jt1 = new javax.swing.JTextField();
        jt2 = new javax.swing.JTextField();
        ans = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jC1 = new javax.swing.JComboBox<>();
        jC2 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jPanel1.setForeground(new java.awt.Color(242, 242, 242));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Quantity");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Result");

        jt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt1ActionPerformed(evt);
            }
        });

        jt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jt2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(277, 277, 277)
                                .addComponent(ans))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jt1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel2)))
                .addContainerGap(80, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(321, 321, 321)
                .addComponent(ans)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jt1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jt2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 100, 363, 340);

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jButton1.setText("Convert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(420, 310, 97, 42);

        jButton2.setBackground(new java.awt.Color(204, 204, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(540, 310, 97, 42);

        jButton3.setBackground(new java.awt.Color(204, 204, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(480, 370, 97, 42);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("From:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(410, 140, 50, 25);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("To:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(420, 210, 40, 25);

        jC1.setBackground(new java.awt.Color(204, 204, 255));
        jC1.setForeground(new java.awt.Color(204, 204, 255));
        jC1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Feet", "Meters", "Pounds", "Kgs", "Farenheit", "Celsius" }));
        jPanel1.add(jC1);
        jC1.setBounds(480, 140, 167, 22);

        jC2.setBackground(new java.awt.Color(204, 204, 255));
        jC2.setForeground(new java.awt.Color(204, 204, 255));
        jC2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Feet", "Meters", "Pounds", "Kgs", "Farenheit", "Celsius" }));
        jPanel1.add(jC2);
        jC2.setBounds(480, 210, 164, 22);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        jLabel5.setText("Metric Converter");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(170, 20, 373, 50);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nathan.Davids\\Downloads\\pawel-czerwinski-ncgbTwIZhNU-unsplash.jpg")); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(0, 0, 680, 460);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jt1.setText("");
        jt2.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String box1 = (String)jC1.getSelectedItem ();
        String box2 = (String)jC2.getSelectedItem ();

        if (box1.equals("Feet")&& (box2.equals("Meters")))
        {
            double c = Double.parseDouble(jt1.getText());
            double f = (double) Math.round(c / 3.281);
            jt2.setText(String.format("%.2f", f));
        }
        if (box1.equals("Meters") && box2.equals("Feet"))
        {
            double c = Double.parseDouble(jt1.getText());
            double f = (double) Math.round(c * 3.281 );
            jt2.setText(String.format("%.2f", f));
        }
        if (box1.equals("Feet") && box2.equals("Feet"))
        {
            double c = Double.parseDouble(jt1.getText());
            double f = (double) Math.round(c / 1);
            jt2.setText(String.format("%.2f", f));
        }
        if (box1.equals("Meters") && box2.equals("Meters"))
        {
            double c = Double.parseDouble(jt1.getText());
            double f = (double) Math.round(c / 1);
            jt2.setText(String.format("%.2f", f));
        }
        if (box1.equals("Pounds")&& (box2.equals("Kgs")))
        {
            double c = Double.parseDouble(jt1.getText());
            double f = (double) Math.round(c / 2.205);
            jt2.setText(String.format("%.2f", f));
        }
        if (box1.equals("Kgs")&& (box2.equals("Pounds")))
        {
            double c = Double.parseDouble(jt1.getText());
            double f = (double) Math.round(c * 2.205);
            jt2.setText(String.format("%.2f", f));
        }
        if (box1.equals("Pounds")&& (box2.equals("Pounds")))
        {
            double c = Double.parseDouble(jt1.getText());
            double f = (double) Math.round(c / 1);
            jt2.setText(String.format("%.2f", f));
        }
        if (box1.equals("Kgs")&& (box2.equals("Kgs")))
        {
            double c = Double.parseDouble(jt1.getText());
            double f = (double) Math.round(c / 1);
            jt2.setText(String.format("%.2f", f));
        }
        if (box1.equals("Farenheit")&& (box2.equals("Celsius")))
        {
            double c = Double.parseDouble(jt1.getText());
            double f = (double) Math.round((c-32)*5/9 );
            jt2.setText(String.format("%.2f", f));
        }
        if (box1.equals("Celsius")&& (box2.equals("Farenheit")))
        {
            double c = Double.parseDouble(jt1.getText());
            double f = (double) Math.round((c*9/5)+32 );
            jt2.setText(String.format("%.2f", f));
        }
        if (box1.equals("Farenheit")&& (box2.equals("Farenheit")))
        {
            double c = Double.parseDouble(jt1.getText());
            double f = (double) Math.round(c / 1);
            jt2.setText(String.format("%.2f", f));
        }
        if (box1.equals("Celsius")&& (box2.equals("Celsius")))
        {
            double c = Double.parseDouble(jt1.getText());
            double f = (double) Math.round(c / 1);
            jt2.setText(String.format("%.2f", f));
        }
        if (box1.equals("Feet")&& (box2.equals("Pounds")))
        {
            jt2.setText("Invalid Option");
        }
        if (box1.equals("Feet")&& (box2.equals("Kgs")))
        {
            jt2.setText("Invalid Option");
        }
        if (box1.equals("Feet")&& (box2.equals("Farenheit")))
        {
            jt2.setText("Invalid Option");
        }
        if (box1.equals("Feet")&& (box2.equals("Celsius")))
        {
            jt2.setText("Invalid Option");
        }
        if (box1.equals("Celsius")&& (box2.equals("Feet")))
        {
            jt2.setText("Invalid Option");
        }
        if (box1.equals("Meters")&& (box2.equals("Celsius")))
        {
            jt2.setText("Invalid Option");
        }
        if (box1.equals("Pounds")&& (box2.equals("Farenheit")))
        {
            jt2.setText("Invalid Option");
        }
        if (box1.equals("Kgs")&& (box2.equals("Farenheit")))
        {
            jt2.setText("Invalid Option");
        }
        if (box1.equals("Farenheit")&& (box2.equals("Kgs")))
        {
            jt2.setText("Invalid Option");
        }
        if (box1.equals("Farenheit")&& (box2.equals("Pounds")))
        {
            jt2.setText("Invalid Option");
        }
        if (box1.equals("Celsius")&& (box2.equals("Pounds")))
        {
            jt2.setText("Invalid Option");
        }
        if (box1.equals("Feet")&& (box2.equals("Celsius")))
        {
            jt2.setText("Invalid Option");
        }
        if (box1.equals("Pounds")&& (box2.equals("Celsius")))
        {
            jt2.setText("Invalid Option");
        }
        if (box1.equals("Celsius")&& (box2.equals("Kgs")))
        {
            jt2.setText("Invalid Option");
        }
        if (box1.equals("Kgs")&& (box2.equals("Celsius")))
        {
            jt2.setText("Invalid Option");
        }
        if (box1.equals("Celsius")&& (box2.equals("Meter")))
        {
            jt2.setText("Invalid Option");
        }
        if (box1.equals("Farenheit")&& (box2.equals("Feet")))
        {
            jt2.setText("Invalid Option");
        }
        if (box1.equals("Meters")&& (box2.equals("Farenheit")))
        {
            jt2.setText("Invalid Option");
        }
        if (box1.equals("Farenheit")&& (box2.equals("Meters")))
        {
            jt2.setText("Invalid Option");
        }
        if (box1.equals("Kgs")&& (box2.equals("Feet")))
        {
            jt2.setText("Invalid Option");
        }
        if (box1.equals("Meters")&& (box2.equals("Kgs")))
        {
            jt2.setText("Invalid Option");
        }
        if (box1.equals("Kgs")&& (box2.equals("Meters")))
        {
            jt2.setText("Invalid Option");
        }
        if (box1.equals("Pounds")&& (box2.equals("Feet")))
        {
            jt2.setText("Invalid Option");
        }
        if (box1.equals("Meters")&& (box2.equals("Pounds")))
        {
            jt2.setText("Invalid Option");
        }
        if (box1.equals("Pounds")&& (box2.equals("Meters")))
        {
            jt2.setText("Invalid Option");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt2ActionPerformed

    private void jt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MetricConverterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MetricConverterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MetricConverterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MetricConverterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MetricConverterGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ans;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jC1;
    private javax.swing.JComboBox<String> jC2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jt1;
    private javax.swing.JTextField jt2;
    // End of variables declaration//GEN-END:variables
}
